### ISSUE TITLE
Error flag redefined: ginkgo.seed

### ISSUE THREAD

**Issue by rauizab** [cloudfoundry/cf-smoke-tests#32]
Hi

I am trying to run the smoke tests under go 1.8 but I get this error:

> + ./bin/test
> + command -v go
> + [[ -z /go:/tmp/build/158c3bf0/smokeTests ]]
> + export PATH=/go:/tmp/build/158c3bf0/smokeTests/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> + PATH=/go:/tmp/build/158c3bf0/smokeTests/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> + command -v ginkgo
> + mkdir -p /go:/tmp/build/158c3bf0/smokeTests/src/github.com/onsi
> + cp -R vendor/github.com/onsi/ginkgo /go:/tmp/build/158c3bf0/smokeTests/src/github.com/onsi/ginkgo
> + go install -v github.com/onsi/ginkgo/ginkgo
> github.com/onsi/ginkgo/ginkgo/interrupthandler
> github.com/onsi/ginkgo/ginkgo/convert
> github.com/onsi/ginkgo/ginkgo/nodot
> github.com/onsi/ginkgo/ginkgo/testsuite
> github.com/onsi/ginkgo/ginkgo/testrunner
> github.com/onsi/ginkgo/ginkgo/watch
> github.com/onsi/ginkgo/ginkgo
> + export CF_DIAL_TIMEOUT=11
> + CF_DIAL_TIMEOUT=11
> + ginkgo -r --succinct -slowSpecThreshold=300
> /tmp/ginkgo227198536/etcd_cluster_check.test flag redefined: ginkgo.seed
> panic: /tmp/ginkgo227198536/etcd_cluster_check.test flag redefined: ginkgo.seed
>
> goroutine 1 [running]:
> flag.(*FlagSet).Var(0xc42001a0c0, 0x9fbb40, 0xacac80, 0xc42012c1f0, 0xb, 0x83ed4e, 0x2a)
>       /usr/local/go/src/flag/flag.go:793 +0x420
> flag.(*FlagSet).Int64Var(0xc42001a0c0, 0xacac80, 0xc42012c1f0, 0xb, 0x5953c6ed, 0x83ed4e, 0x2a)
>       /usr/local/go/src/flag/flag.go:618 +0x7https://github.com/onsi/ginkgo/issues/2341
> github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/onsi/ginkgo/config.Flags(0xc42001a0c0, 0xc420049de0, 0x7, 0xc420049e01)
>       /go/src/github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/onsi/ginkgo/config/config.go:66 +0xee
> github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/onsi/ginkgo.init.1()
>       /go/src/github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:54 +0x59
> github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/onsi/ginkgo.init()
>       /go/src/github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:570 +0x9d
> github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/commandreporter.init()
>       /go/src/github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/commandreporter/command_reporter.go:53 +0x5d
> github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/internal.init()
>       /go/src/github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/internal/starter.go:8 +0x44
> github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/commandstarter.init()
>       /go/src/github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/commandstarter/command_starter.go:25 +0x4e
> github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/cf.init()
>       /go/src/github.com/cloudfoundry/cf-smoke-tests/vendor/github.com/cloudfoundry-incubator/cf-test-helpers/cf/cf.go:13 +0x44
> github.com/cloudfoundry/cf-smoke-tests/smoke.init()
>       /go/src/github.com/cloudfoundry/cf-smoke-tests/smoke/helpers.go:58 +0x5d
> _/tmp/build/158c3bf0/smokeTests/smoke/etcd_cluster_check.init()
>       /tmp/build/158c3bf0/smokeTests/smoke/etcd_cluster_check/init_test.go:79 +0x64
> main.init()
>       _/tmp/build/158c3bf0/smokeTests/smoke/etcd_cluster_check/_test/_testmain.go:46 +0x53
>
> Ginkgo ran 1 suite in 1.390824715s
> Test Suite Failed

What could it be? 
Is it related to https://github.com/onsi/ginkgo/issues/285? or https://github.com/onsi/ginkgo/issues/234?

**Comment by rauizab** [comment]
Hi

This worked for me as explain in ginkgo#234

rm -rf vendor/github.com/onsi/ginkgo/extensions/table
mv /go/src/github.com/onsi/ginkgo/extensions/table vendor/github.com/onsi/ginkgo/extensions
